server:
  port: 8091
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Java5UserProfileDb
    password: burhan71
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true